[tools]
go = "1.26"
java = "25"
node = "24"
python = "3.14"
pnpm = "latest"
ghq = "latest"
gh = "latest"
"github:k1LoW/roots" = "latest"
gitleaks = "8.22.1"
maven = "latest"
ripgrep = "latest"
yq = "latest"
actionlint = "latest"
hadolint = "latest"
shfmt = "latest"
devcontainer-cli = "latest"
delta = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true
