[tools]
go = "1.26"
java = "25"
node = "24"
python = "3.14"
pnpm = "11.20.0"
ghq = "1.10.1"
gh = "2.97.0"
"github:k1LoW/roots" = "0.4.1"
gitleaks = "8.22.1"
maven = "3.9.16"
ripgrep = "15.2.0"
yq = "4.53.3"
actionlint = "1.7.12"
hadolint = "2.15.1"
shfmt = "3.13.1"
devcontainer-cli = "0.88.0"
delta = "0.19.2"

[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true
